apiVersion: charlescd.io/v1
kind: CharlesDeployment
metadata:
  name: deploy-test

spec:
  components:
    - name: quiz-app-backend
      image: thallesf/quiz-app:1.0
      chart: https://api.github.com/repos/zupit/charlescd/contents/samples/quiz-app/charts/quiz-app-backend?ref=update-tgz
      provider: GITHUB
      namespace: default
      token: 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
  childResources: []
