apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charlesdeployments.charlescd.io
spec:
  group: charlescd.io
  versions:
    - name: v1
      served: true
        # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      tag:
                        type: string
                      chart:
                        type: string
                    required:
                      - name
                      - tag
                      - chart
                      - provider
  scope: Namespaced
  names:
    plural: charlesdeployments
    singular: charlesdeployments
    kind: CharlesDeployment
    shortNames:
    - cd
