apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: charlesdeployments.charlescd.io
spec:
  group: charlescd.io
  versions:
    - name: v1
      served: true
        # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                childResources:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      name:
                        type: string
                      plural:
                        type: string
                      componentName:
                          type: string
                components:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      chart:
                        type: string
                      provider:
                          type: string
                      namespace:
                        type: string
                      token:
                        type: string
                    required:
                      - name
                      - chart
                      - provider
                      - namespace
                      - image
  scope: Namespaced
  names:
    plural: charlesdeployments
    singular: charlesdeployment
    kind: CharlesDeployment
    shortNames:
    - cd
