apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: java-operator
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metacontroller
subjects:
  - kind: ServiceAccount
    name:  java-operator-sdk-helm
    namespace: default
roleRef:
  kind: ClusterRole
  name: java-operator
  apiGroup: rbac.authorization.k8s.io